Fix minor issues in devicelocation sample code
Telefonica/opengateway-developers-website pull request #50
Opened 2024-11-28 16:21 UTC by gitmai

2024-11-28 17:08 UTC, diegotid requested changes
Faltaría:
- Segundo párrafo sobre llamar por HTTP y enlace a Postman
- Falta todo el Frontend flow
- Callout avisando que es sample code y hay cosas que cambiar
- El most likely de usar el API desde backend es para SIM Swap, pero para Device Location no aplica, porque puede haber muchos casos de uso desde frontend
- Falta la intro que va debajo del título "Authorization"
- Faltan los tabs del resto de lenguajes en las cajas de código
- Falta la intro que va debajo del título "API usage"

2024-12-02 13:00 UTC, diegotid requested changes
Change the introduction paragraphs on each row, and wait por @lufuOGW approval (as original code contributor) to merge

And please, no PR without a description

2024-12-02 16:47 UTC, diegotid requested changes
I like your texts!

Some rewording though

2024-12-02 16:47 UTC, diegotid commented on catalog/devicelocation/samplecode_devicelocation.md
> +There are many use cases where it might be interesting for the flow to start from a frontend device. For example, checking the status of your pets when you hire a walking service, so that it can send
```suggestion
There are additional use cases where the app on the end-user’s device directly utilizes the Device Location API to enable features. Examples include checking in at a venue or accessing content restricted to specific geographic zones.
```

2024-12-02 16:47 UTC, diegotid commented on catalog/devicestatus/samplecode_devicestatus.md
> +The consumption of this api in a backend flow opens up many possibilities, from anti-fraud services such as bank transaction verification, logistics (for courier services or IoT), or even for travel
```suggestion
The consumption of this API in a backend flow opens up many possibilities, from anti-fraud services such as bank transaction verification, logistics (for courier services or IoT), and even personalized campaigns by tourism operators.
```

2024-12-02 16:47 UTC, diegotid commented on catalog/devicestatus/samplecode_devicestatus.md
> +Although it is not necessary for the user’s device to participate in the flow for the device status, it is important to consider that the roaming status can be used as an additional authentication fa
```suggestion
While some use cases of the Device Status API do not involve the user’s device in the API usage flow, others can utilize the API to check roaming status directly from the frontend. For example, a mobile application could use it as an additional authentication factor or to adjust its content based on the user’s country.
```

2024-12-04 09:02 UTC, lufuOGW approved these changes
All the changes seem correct to me. Nice work!

2024-12-04 09:28 UTC, diegotid approved these changes
Well done! 👏🏼

2024-12-04 09:35 UTC, merged